import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import '../../src/output.css';
import Providers from "./provider";
import { ChatProvider } from "@/components/common/chatContext";
import { VideoCallProvider } from "@/components/common/videoCallContext";
import VideoCall from "@/components/common/GlocalCallModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
  {/* Tải Stringee Web SDK với defer */}
  <script
    src="https://cdn.stringee.com/sdk/web/latest/stringee-web-sdk.min.js"
    defer
  />
  {/* Loại bỏ stringee.js để tránh xung đột, chỉ giữ một phiên bản SDK */}
  <script src="https://cdn.stringee.com/stringee-js-sdk/latest/stringee.js" defer></script>
  {/* Sử dụng defer cho các script khác */}
  <script
    type="text/javascript"
    src="/jquery-3.2.1.min.js"
    defer
  />
  <script
    type="text/javascript"
    src="/latest_sdk_bundle.min.js"
    defer
  />
  <script
    type="text/javascript"
    src="/call2_demo.js"
    defer
  />
  <script type="text/javascript" src="https://cdn.stringee.com/sdk/web/latest/stringee-web-sdk.min.js" defer></script>
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Correctly wrap your children with ToastProvider */}
        <Providers>
          <VideoCallProvider>
  <ChatProvider>
    {children}
    <VideoCall />
  </ChatProvider>
</VideoCallProvider>
        </Providers>
      </body>
    </html>
  );
}
