name: Dockerized App Deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24700
          script: |
            cd /root/lawohproject/lawohprojectFe/LawohFe
            git fetch origin
            git checkout master
            git pull origin master
            docker build -t lawohfe .
            docker stop lawohfe-container || true
            docker rm lawohfe-container || true
            docker run -d --name lawohfe-container -p 4001:3000 lawohfe
            docker ps -a
            docker images
